language: objective-c
matrix:
  include:
    - osx_image: xcode10.2

before_install:
  - bundle install --path=vendor/bundle --clean
  - carthage bootstrap --no-use-binaries --platform ios

script:
    - bundle exec fastlane ios test

cache:
  directories:
    - Carthage